CREATE DATABASE FLASKEXAMPLE2;

USE FLASKEXAMPLE2;

CREATE TABLE USERS(
	FULLNAME VARCHAR(100),
    EMAIL VARCHAR(30) PRIMARY KEY,
    MOBILE VARCHAR(12),
    PWD VARCHAR(50)
);

select * from users;

CREATE TABLE TASKS(
	EMAIL varchar(100),
    TASKNAME varchar(100),
    TASKTIME TIME,
    TASKDESCRIPTION VARCHAR(500)
);

SELECT * FROM TASKS;